# Missing Values in Pandas
Task 18 - Day 18

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Asha", "Raj", "Meena", "Vikram", "Priya", "Karan", "Nisha", "Arjun"],
    "Age": [23, 25, np.nan, 24, 26, 21, np.nan, 23],
    "Department": ["Sales", "IT", "HR", None, "Sales", "HR", "IT", "Sales"],
    "Salary": [45000, np.nan, 38000, 71000, np.nan, 41000, 68000, 47000],
    "Experience": [2, 4, 1, 6, 3, np.nan, 5, 2],
})
df

     Name   Age Department   Salary  Experience
0    Asha  23.0      Sales  45000.0         2.0
1     Raj  25.0         IT      NaN         4.0
2   Meena   NaN         HR  38000.0         1.0
3  Vikram  24.0        NaN  71000.0         6.0
4   Priya  26.0      Sales      NaN         3.0
5   Karan  21.0         HR  41000.0         NaN
6   Nisha   NaN         IT  68000.0         5.0
7   Arjun  23.0      Sales  47000.0         2.0

## Missing-value summary

In [2]:
df.isna()

    Name    Age  Department  Salary  Experience
0  False  False       False   False       False
1  False  False       False    True       False
2  False   True       False   False       False
3  False  False        True   False       False
4  False  False       False    True       False
5  False  False       False   False        True
6  False   True       False   False       False
7  False  False       False   False       False

In [3]:
print(df.isna().sum())

Name          0
Age           2
Department    1
Salary        2
Experience    1
dtype: int64

In [4]:
print(df.notna().sum())

Name          8
Age           6
Department    7
Salary        6
Experience    7
dtype: int64

In [5]:
print("Total missing cells:", df.isna().sum().sum())

Total missing cells: 6

In [6]:
print(df.isna().mean() * 100, sep="")

Name           0.0
Age           25.0
Department    12.5
Salary        25.0
Experience    12.5
dtype: float64

## Examples using isna() and notna()

In [7]:
# rows where Age is missing
print(df[df["Age"].isna()])

    Name  Age Department   Salary  Experience
2  Meena  NaN         HR  38000.0         1.0
6  Nisha  NaN         IT  68000.0         5.0

In [8]:
# rows where Salary is present (not missing)
print(df[df["Salary"].notna()])

     Name   Age Department   Salary  Experience
0    Asha  23.0      Sales  45000.0         2.0
2   Meena   NaN         HR  38000.0         1.0
3  Vikram  24.0        NaN  71000.0         6.0
5   Karan  21.0         HR  41000.0         NaN
6   Nisha   NaN         IT  68000.0         5.0
7   Arjun  23.0      Sales  47000.0         2.0

## Dropping missing values

In [9]:
# drop any row containing at least one missing value
print(df.dropna())

    Name   Age Department   Salary  Experience
0   Asha  23.0      Sales  45000.0         2.0
7  Arjun  23.0      Sales  47000.0         2.0

In [10]:
# drop rows missing only in a specific column
print(df.dropna(subset=["Age"]))

     Name   Age Department   Salary  Experience
0    Asha  23.0      Sales  45000.0         2.0
1     Raj  25.0         IT      NaN         4.0
3  Vikram  24.0        NaN  71000.0         6.0
4   Priya  26.0      Sales      NaN         3.0
5   Karan  21.0         HR  41000.0         NaN
7   Arjun  23.0      Sales  47000.0         2.0

In [11]:
# drop any column containing at least one missing value
print(df.dropna(axis=1))

     Name
0    Asha
1     Raj
2   Meena
3  Vikram
4   Priya
5   Karan
6   Nisha
7   Arjun

## Filling missing values

In [12]:
# simplest approach - fill everything with 0
print(df.fillna(0))

     Name   Age Department   Salary  Experience
0    Asha  23.0      Sales  45000.0         2.0
1     Raj  25.0         IT      0.0         4.0
2   Meena   0.0         HR  38000.0         1.0
3  Vikram  24.0          0  71000.0         6.0
4   Priya  26.0      Sales      0.0         3.0
5   Karan  21.0         HR  41000.0         0.0
6   Nisha   0.0         IT  68000.0         5.0
7   Arjun  23.0      Sales  47000.0         2.0

In [13]:
# a more careful approach - different strategy per column
df_cleaned = df.copy()
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())
df_cleaned["Salary"] = df_cleaned["Salary"].fillna(df_cleaned["Salary"].median())
df_cleaned["Experience"] = df_cleaned["Experience"].fillna(df_cleaned["Experience"].median())
df_cleaned["Department"] = df_cleaned["Department"].fillna("Unknown")

df_cleaned

     Name        Age Department   Salary  Experience
0    Asha  23.000000      Sales  45000.0         2.0
1     Raj  25.000000         IT  46000.0         4.0
2   Meena  23.666667         HR  38000.0         1.0
3  Vikram  24.000000    Unknown  71000.0         6.0
4   Priya  26.000000      Sales  46000.0         3.0
5   Karan  21.000000         HR  41000.0         3.0
6   Nisha  23.666667         IT  68000.0         5.0
7   Arjun  23.000000      Sales  47000.0         2.0

## The cleaned dataset

In [14]:
print(df_cleaned.isna().sum())

Name          0
Age           0
Department    0
Salary        0
Experience    0
dtype: int64

In [15]:
df_cleaned

     Name        Age Department   Salary  Experience
0    Asha  23.000000      Sales  45000.0         2.0
1     Raj  25.000000         IT  46000.0         4.0
2   Meena  23.666667         HR  38000.0         1.0
3  Vikram  24.000000    Unknown  71000.0         6.0
4   Priya  26.000000      Sales  46000.0         3.0
5   Karan  21.000000         HR  41000.0         3.0
6   Nisha  23.666667         IT  68000.0         5.0
7   Arjun  23.000000      Sales  47000.0         2.0

## Interview questions

**What are missing values?**
Entries in a dataset where no data was recorded for that cell. Pandas represents them as `NaN` (Not a Number) for numeric and object columns, or `None` for general Python objects. They can show up from incomplete data entry, merged datasets with mismatched records, or sensors/surveys that didn't capture every field.

**What are common ways to handle missing values?**
Dropping rows or columns with `dropna()` when missing data is rare and removing it won't bias the analysis; filling with a constant, mean, or median using `fillna()` when the column should keep every row but needs a reasonable placeholder; or filling categorical gaps with a label like "Unknown" to keep the row without guessing a category. The right choice depends on how much is missing and why.

**When should you avoid simply dropping missing rows?**
When missingness is common rather than rare — dropping every row with any gap can throw away a large share of the dataset, as the example above shows (`dropna()` kept only 1 of 8 rows). It's also risky when missing values aren't random: if a particular group tends to have more gaps (e.g. one department didn't report salary), dropping those rows biases the remaining data toward the groups that did report.